#!/usr/bin/env python3
r"""
indicators_lib.py — the fixed frame of progress indicators, and the per-unit view over it.

`documentation/progress-report-redesign.md` is the decision record. The one sentence that
matters here: **the progress report's rows are chosen by design, not by arrival**. The frame is
the same indicators for every country, and what varies between countries is only which of
them the base can say anything about.

Two files, and they are different kinds of thing.

`lookups/indicators.csv` is **the frame** — the canonical list, hand-maintained, generated by
nothing, and the same for all 54 countries. It carries `indicator_id` plus the wireframe's own
columns. An indicator is added by editing this file; `prep/progress-report-wireframe-v2.csv` was
the drafting copy it was minted from and is retired, because two copies of one list with nothing
comparing them is the drift `scripts/lint-shared-assets.py` exists to catch, and there would be no
lint here.

`outputs/reports/{unit}/indicators.csv` is **one country's view of the frame** — the mapping from
ledger rows to indicators, the drafted prose, and the Progress value. It is maintained like the
ledger and never rebuilt: a re-render costs a render, not a redraft. `load_unit()` reads it.

**Absolute path from this file, never relative** — the same rule, and for the same reason, as
`taxonomy_lib`'s docstring gives at length. The compile stage runs from a workroot in which
`lookups/` is a junction to **OSINT's** `lookups/`, not Corpus's. A relative read of
`lookups/indicators.csv` there resolves into another repository's tree, finds nothing, and the
renderer would then render a frame of No evidence rows over 54 real reports while reporting a normal
build. `Path(__file__).resolve()` is what keeps this Corpus's own tree; `.resolve()` because
`scripts/` is itself a junction in the workroot.
"""
from __future__ import annotations

import csv
import os
from pathlib import Path

CORPUS = Path(__file__).resolve().parent.parent
INDICATORS_CSV = CORPUS / "lookups" / "indicators.csv"

# The per-unit file's columns. `row_ids` is the mapping, the two prose fields are the drafted
# text, `progress` is the vocabulary value. There is deliberately no `sources` column: the
# citations are inline in the prose, on the claim they support, and `row_ids` carries the
# evidence linkage — a third place to name a source would be the one nothing renders.
UNIT_FIELDS = ("indicator_id", "progress", "summary", "developments", "row_ids")

# The maturity assessment's stage columns (`maturity-assessment.md` §6), after the mapping's. They are
# set by `maturity-assess.py apply` and by nothing else. `stage_rows` is the subset of `row_ids` that
# satisfies the anchor. Every column is empty on an indicator with no stage. `load_unit()` reads a
# file with them or without them; `progress` leaves at G1.
STAGE_FIELDS = ("stage", "stage_rows", "value", "unit", "value_year", "value_source",
                "next_milestone", "due", "assessed_on", "reassessed", "qualifier")
UNIT_FIELDS = UNIT_FIELDS + STAGE_FIELDS

# The maturity assessment's three frame columns (`documentation/maturity-assessment.md` §4 and
# `adding-an-indicator.md` §§3, 10). `kind` picks the rubric family; `assessed = 0` keeps a row
# for its id and its mapped rows without staging it, and `retired` dates when that began. An id
# is never deleted, so retirement is these two cells and nothing else.
KINDS = ("instrument", "system", "measure")

_frame: list[dict] | None = None


def frame() -> list[dict]:
    """Every indicator, in the wireframe's own display order.

    Each row is `{indicator_id, subject, indicator, chapter, topic, kind, assessed, retired}` —
    `subject` being the taxonomy Level-2 key the indicator hangs off, `chapter` its Level-1
    parent, `topic` the Level-2 label the report prints in its first column, and the last three
    the maturity assessment's (`KINDS`; `assessed` a bool; `retired` a date or empty). Every row
    is returned, assessed or not: the progress report still prints all of them until it retires.
    """
    global _frame
    if _frame is None:
        if not INDICATORS_CSV.exists():
            raise SystemExit(
                f"indicators_lib: {INDICATORS_CSV} is missing.\n"
                "  It is the frame every country progress report is drawn against, "
                "hand-maintained and generated by nothing, so a build cannot make one.")
        with open(INDICATORS_CSV, encoding="utf-8-sig", newline="") as fh:
            rows = list(csv.DictReader(fh))
        want = {"indicator_id", "Topic Sort", "Indicator Sort", "Topic L1", "Topic", "Topic L2",
                "Progress indicator", "kind", "assessed", "retired"}
        missing = want - set(rows[0] if rows else {})
        if missing:
            raise SystemExit(
                f"indicators_lib: {INDICATORS_CSV} is missing column(s) "
                f"{', '.join(sorted(missing))}.")
        seen: set[str] = set()
        out = []
        for r in rows:
            iid = (r["indicator_id"] or "").strip()
            if not iid:
                raise SystemExit(f"indicators_lib: a row of {INDICATORS_CSV} has no indicator_id "
                                 f"— {r.get('Progress indicator')!r}")
            if iid in seen:
                # Ids are never reissued and never renamed (§8), so a duplicate is not a merge
                # to resolve at render time — it is two indicators claiming one identity, and
                # whichever the renderer picked would silently drop the other.
                raise SystemExit(f"indicators_lib: duplicate indicator_id {iid!r} in "
                                 f"{INDICATORS_CSV}")
            seen.add(iid)
            kind = (r["kind"] or "").strip()
            assessed = (r["assessed"] or "").strip()
            retired = (r["retired"] or "").strip()
            # An assessed row has to say which ladder it is on, and a row that is not assessed
            # has to say since when; either missing is a frame edit left half done.
            if assessed not in ("0", "1"):
                raise SystemExit(f"indicators_lib: {iid} has assessed = {assessed!r}; "
                                 f"it is 1 or 0")
            if assessed == "1" and kind not in KINDS:
                raise SystemExit(f"indicators_lib: assessed indicator {iid} has kind {kind!r}; "
                                 f"it is one of {', '.join(KINDS)}")
            if assessed == "0" and not retired:
                raise SystemExit(f"indicators_lib: {iid} is not assessed and has no retired "
                                 f"date")
            out.append({
                "indicator_id": iid,
                "subject": (r["Topic L2"] or "").strip(),
                "topic": (r["Topic"] or "").strip(),
                "chapter": (r["Topic L1"] or "").strip(),
                "indicator": (r["Progress indicator"] or "").strip(),
                # Display order only, and never an identity: an id that renumbers when a row is
                # inserted is not an id (§8).
                "sort": (int(r["Topic Sort"] or 0), int(r["Indicator Sort"] or 0)),
                "kind": kind,
                "assessed": assessed == "1",
                "retired": retired,
            })
        _frame = sorted(out, key=lambda r: r["sort"])
    return _frame


def ids() -> set[str]:
    return {r["indicator_id"] for r in frame()}


def assessed() -> list[dict]:
    """The frame the maturity assessment stages: every row with `assessed = 1`, in order."""
    return [r for r in frame() if r["assessed"]]


def by_chapter(order: list[str]) -> list[tuple[str, list[dict]]]:
    """[(chapter, [indicator, ...])] in `order` — the taxonomy's Level-1 chapters.

    The order is passed in rather than read here so that the document's chapter sequence has one
    source, `taxonomy_lib`, and cannot drift from the status report's beside it. A chapter the
    frame holds nothing for is not returned; with the frame covering every subject that cannot
    currently arise, and it is a cheaper thing to allow than to assert.
    """
    groups: dict[str, list[dict]] = {}
    for r in frame():
        groups.setdefault(r["chapter"], []).append(r)
    return [(c, groups[c]) for c in order if c in groups]


def unit_path(reports_dir: str, unit: str) -> str:
    return os.path.join(reports_dir, unit, "indicators.csv")


def load_unit(reports_dir: str, unit: str) -> dict[str, dict] | None:
    """`{indicator_id: row}` for one unit, or None where the file does not exist.

    **None is not an empty mapping and the caller must not treat it as one.** An absent file means
    the mapping pass has not run for this unit; an empty one would mean it ran and found nothing.
    Rendering the first as the second writes a frame of No evidence rows over a real report and reports a
    normal build — the same shape of unrecoverable success that `initialised()` guards the status
    baseline against, and `render_progress()` refuses it for the same reason.
    """
    path = unit_path(reports_dir, unit)
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8-sig", newline="") as fh:
        rows = list(csv.DictReader(fh))
    out: dict[str, dict] = {}
    for r in rows:
        iid = (r.get("indicator_id") or "").strip()
        if iid:
            out[iid] = r
    return out


def row_ids(row: dict | None) -> list[str]:
    """The ledger rows an indicator maps to. Pipe-separated, like the ledger's own `sources`."""
    if not row:
        return []
    return [s.strip() for s in (row.get("row_ids") or "").split("|") if s.strip()]
