#!/usr/bin/env python3
r"""
taxonomy_lib.py — the subject taxonomy, from `lookups/taxonomy.csv`.

    from taxonomy_lib import labels, label, level1, sort_key, keys
    labels()              -> {"dpi.pay": "Digital Payments and Fintech", ...}
    label("dpi.registry") -> "Registries"
    level1("dpi.registry")-> "DPI"
    sort_key("gov.policy")-> 1
    keys()                -> every key in the file's own order

**`lookups/taxonomy.csv` is the display vocabulary** *(Bill, 2026-08-19)*:
four columns, `Sort order,Key,Level 1,Level 2`, hand-maintained and generated by
nothing. It is Corpus's, not OSINT's — the *slugs* are OSINT's controlled
vocabulary and the authority for what may be tagged, but how a slug is written on
a page is a publishing decision, and it was being made three different ways.

The immediate reason it exists: `lookups/taxonomy.md` is prose as well as
vocabulary, and its `dpi.registry` entry carries a 558-character ruling about
where registry material files. Two of the three parsers in this repo read that
whole paragraph as the label, and it reached the site — the sector row of three
countries' pivot tables, the catalogue's topic filter, and every published finance
CSV. A CSV column cannot hold a paragraph of process notes and remain a column.

**Labels here; ordering not yet.** The file also carries a sort order, and it is
not the order `lookups/taxonomy.md` implies — this file opens on Governance, the
markdown on ICT Infrastructure. Reports and topic pages still take both order and
labels from `vault_lib.load_taxonomy()`, so switching them is a change of sequence
on every report as well as of wording, and Bill is reviewing the pages first. When
he says, `sort_key` is what they should use.

**Absolute path from this file, never relative, and the move into `lookups/`
makes that load-bearing** *(2026-08-21; it lived at `site/metadata/taxonomy.csv`
until then)*. The compile stage runs from a workroot that junctions `raw/`,
`lookups/`, `scripts/` and `outputs/`, and `.workroot/lookups` is **OSINT's**
`lookups/`, not Corpus's. Under the old path a relative read resolved to nothing
and failed loudly; under this one it would resolve to a real directory belonging
to another repository and fail silently or read the wrong file. `Path(__file__)
.resolve()` is what keeps this Corpus's own tree — `.resolve()` because `scripts/`
is itself a junction in the workroot. `status_lib.IIAG_CSV` reaches
`lookups/iiag-profiles.csv` the same way, for the same reason.
"""
from __future__ import annotations

import csv
from pathlib import Path

CORPUS = Path(__file__).resolve().parent.parent
TAXONOMY_CSV = CORPUS / "lookups" / "taxonomy.csv"

_rows: list[dict] | None = None


def _load() -> list[dict]:
    global _rows
    if _rows is None:
        if not TAXONOMY_CSV.exists():
            raise SystemExit(
                f"taxonomy_lib: {TAXONOMY_CSV} is missing.\n"
                "  It is the display vocabulary for every subject slug on the site, "
                "hand-maintained and generated by nothing, so a build cannot make one.")
        with open(TAXONOMY_CSV, encoding="utf-8-sig", newline="") as fh:
            rows = list(csv.DictReader(fh))
        want = {"Sort order", "Key", "Level 1", "Level 2"}
        missing = want - set(rows[0] if rows else {})
        if missing:
            raise SystemExit(
                f"taxonomy_lib: {TAXONOMY_CSV.name} is missing column(s) "
                f"{', '.join(sorted(missing))}. Expected: {', '.join(sorted(want))}.")
        _rows = sorted(rows, key=lambda r: int(r["Sort order"]))
    return _rows


def labels() -> dict[str, str]:
    """`{slug: Level 2}` — the label a reader sees."""
    return {r["Key"]: r["Level 2"] for r in _load()}


def level1s() -> dict[str, str]:
    return {r["Key"]: r["Level 1"] for r in _load()}


def keys() -> list[str]:
    """Every slug, in the file's own order."""
    return [r["Key"] for r in _load()]


def label(key: str) -> str:
    """The label, or the slug itself if the taxonomy does not carry it.

    Falling back to the slug rather than raising is deliberate: a slug that has
    left the vocabulary should still let a page build, and `unknown()` is how a
    caller finds out that it happened."""
    return labels().get(key, key)


def level1(key: str) -> str:
    return level1s().get(key, "")


def sort_key(key: str) -> int:
    """Position in the taxonomy; unknown slugs sort last, in a stable block."""
    order = {r["Key"]: int(r["Sort order"]) for r in _load()}
    return order.get(key, 10_000)


def unknown(used: list[str] | set[str]) -> list[str]:
    """Slugs in `used` the taxonomy does not carry. The fallback in `label()` is
    silent by design, so something has to be able to ask."""
    have = set(labels())
    return sorted({k for k in used if k and k not in have})


if __name__ == "__main__":
    for r in _load():
        print(f"{r['Sort order']:>3}  {r['Key']:20s} {r['Level 1']:20s} {r['Level 2']}")
    print(f"\n{len(_load())} subjects, from {TAXONOMY_CSV.relative_to(CORPUS)}")
